### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by nlvw** [conda-forge/singularity-hpc-feedstock#17]
Hi all, I'm trying to install version 0.0.53 and the install does not install any of the python dependencies for shpc.

Install Log:

```console
$ conda create -n shpc python singularity-hpc
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/nvonwolf/sstack/stacks/conda/testing/envs/shpc

  added / updated specs:
    - python
    - singularity-hpc


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgcc-ng-12.1.0           |      h8d9b700_16         940 KB  conda-forge
    libgomp-12.1.0             |      h8d9b700_16         459 KB  conda-forge
    openssl-3.0.3              |       h166bdaf_0         2.9 MB  conda-forge
    pip-22.1                   |     pyhd8ed1ab_0         1.6 MB  conda-forge
    python-3.10.4              |h2660328_0_cpython        28.6 MB  conda-forge
    setuptools-62.2.0          |  py310hff52083_0         1.3 MB  conda-forge
    singularity-hpc-0.0.53     |     pyhd8ed1ab_0         3.3 MB  conda-forge
    sqlite-3.38.5              |       h4ff8645_0         1.5 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        40.5 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h7f98852_4
  ca-certificates    conda-forge/linux-64::ca-certificates-2021.10.8-ha878542_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.36.1-hea4e1c9_2
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5
  libgcc-ng          conda-forge/linux-64::libgcc-ng-12.1.0-h8d9b700_16
  libgomp            conda-forge/linux-64::libgomp-12.1.0-h8d9b700_16
  libnsl             conda-forge/linux-64::libnsl-2.0.0-h7f98852_0
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h7f98852_1000
  libzlib            conda-forge/linux-64::libzlib-1.2.11-h166bdaf_1014
  ncurses            conda-forge/linux-64::ncurses-6.3-h27087fc_1
  openssl            conda-forge/linux-64::openssl-3.0.3-h166bdaf_0
  pip                conda-forge/noarch::pip-22.1-pyhd8ed1ab_0
  python             conda-forge/linux-64::python-3.10.4-h2660328_0_cpython
  python_abi         conda-forge/linux-64::python_abi-3.10-2_cp310
  readline           conda-forge/linux-64::readline-8.1-h46c0cb4_0
  setuptools         conda-forge/linux-64::setuptools-62.2.0-py310hff52083_0
  singularity-hpc    conda-forge/noarch::singularity-hpc-0.0.53-pyhd8ed1ab_0
  sqlite             conda-forge/linux-64::sqlite-3.38.5-h4ff8645_0
  tk                 conda-forge/linux-64::tk-8.6.12-h27826a3_0
  tzdata             conda-forge/noarch::tzdata-2022a-h191b570_0
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  zlib               conda-forge/linux-64::zlib-1.2.11-h166bdaf_1014


Proceed ([y]/n)? y


Downloading and Extracting Packages
singularity-hpc-0.0. | 3.3 MB    | ############################################################################################# | 100%
sqlite-3.38.5        | 1.5 MB    | ############################################################################################# | 100%
openssl-3.0.3        | 2.9 MB    | ############################################################################################# | 100%
setuptools-62.2.0    | 1.3 MB    | ############################################################################################# | 100%
libgcc-ng-12.1.0     | 940 KB    | ############################################################################################# | 100%
pip-22.1             | 1.6 MB    | ############################################################################################# | 100%
libgomp-12.1.0       | 459 KB    | ############################################################################################# | 100%
python-3.10.4        | 28.6 MB   | ############################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate shpc
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

Error Log:

```console
$ conda activate shpc
$ shpc config get module_base
Traceback (most recent call last):
  File "/home/nvonwolf/sstack/stacks/conda/testing/envs/shpc/lib/python3.10/site-packages/shpc/main/settings.py", line 13, in <module>
    from ruamel_yaml import YAML
ModuleNotFoundError: No module named 'ruamel_yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nvonwolf/sstack/stacks/conda/testing/envs/shpc/bin/shpc", line 10, in <module>
    sys.exit(run_shpc())
  File "/home/nvonwolf/sstack/stacks/conda/testing/envs/shpc/lib/python3.10/site-packages/shpc/client/__init__.py", line 393, in run_shpc
    main(args=args, parser=parser, extra=extra, subparser=helper)
  File "/home/nvonwolf/sstack/stacks/conda/testing/envs/shpc/lib/python3.10/site-packages/shpc/client/config.py", line 12, in main
    from shpc.main import get_client
  File "/home/nvonwolf/sstack/stacks/conda/testing/envs/shpc/lib/python3.10/site-packages/shpc/main/__init__.py", line 6, in <module>
    from .settings import Settings
  File "/home/nvonwolf/sstack/stacks/conda/testing/envs/shpc/lib/python3.10/site-packages/shpc/main/settings.py", line 16, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'
```

You can find a list of Python dependencies [here](https://github.com/singularityhub/singularity-hpc/blob/c3d1099c390c7b34aba42c33065663354169b051/shpc/version.py#L18), though setuptools/setup.py should have handled it.

Manual fix after install:

```console
$ conda install spython Jinja2 jsonschema ruamel requests ruamel_yaml
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/nvonwolf/sstack/stacks/conda/testing/envs/shpc

  added / updated specs:
    - jinja2
    - jsonschema
    - requests
    - ruamel
    - ruamel_yaml
    - spython


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jinja2-3.1.2               |     pyhd8ed1ab_0          99 KB  conda-forge
    jsonschema-4.5.1           |     pyhd8ed1ab_0          57 KB  conda-forge
    ruamel-1.0                 |  py310hff52083_6           5 KB  conda-forge
    semver-2.13.0              |     pyh9f0ad1d_0          15 KB  conda-forge
    spython-0.2.1              |     pyhd8ed1ab_0          68 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         244 KB

The following NEW packages will be INSTALLED:

  attrs              conda-forge/noarch::attrs-21.4.0-pyhd8ed1ab_0
  brotlipy           conda-forge/linux-64::brotlipy-0.7.0-py310h5764c6d_1004
  certifi            conda-forge/linux-64::certifi-2021.10.8-py310hff52083_2
  cffi               conda-forge/linux-64::cffi-1.15.0-py310h0fdd8cc_0
  charset-normalizer conda-forge/noarch::charset-normalizer-2.0.12-pyhd8ed1ab_0
  cryptography       conda-forge/linux-64::cryptography-36.0.2-py310h597c629_1
  idna               conda-forge/noarch::idna-3.3-pyhd8ed1ab_0
  importlib-metadata conda-forge/linux-64::importlib-metadata-4.11.3-py310hff52083_1
  importlib_resourc~ conda-forge/noarch::importlib_resources-5.7.1-pyhd8ed1ab_0
  jinja2             conda-forge/noarch::jinja2-3.1.2-pyhd8ed1ab_0
  jsonschema         conda-forge/noarch::jsonschema-4.5.1-pyhd8ed1ab_0
  markupsafe         conda-forge/linux-64::markupsafe-2.1.1-py310h5764c6d_1
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
  pyopenssl          conda-forge/noarch::pyopenssl-22.0.0-pyhd8ed1ab_0
  pyrsistent         conda-forge/linux-64::pyrsistent-0.18.1-py310h5764c6d_1
  pysocks            conda-forge/linux-64::pysocks-1.7.1-py310hff52083_5
  requests           conda-forge/noarch::requests-2.27.1-pyhd8ed1ab_0
  ruamel             conda-forge/linux-64::ruamel-1.0-py310hff52083_6
  ruamel_yaml        conda-forge/linux-64::ruamel_yaml-0.15.80-py310h6acc77f_1006
  semver             conda-forge/noarch::semver-2.13.0-pyh9f0ad1d_0
  spython            conda-forge/noarch::spython-0.2.1-pyhd8ed1ab_0
  urllib3            conda-forge/noarch::urllib3-1.26.9-pyhd8ed1ab_0
  yaml               conda-forge/linux-64::yaml-0.2.5-h7f98852_2
  zipp               conda-forge/noarch::zipp-3.8.0-pyhd8ed1ab_0

The following packages will be DOWNGRADED:

  openssl                                  3.0.3-h166bdaf_0 --> 1.1.1o-h166bdaf_0
  python                          3.10.4-h2660328_0_cpython --> 3.10.4-h9a8a25e_0_cpython


Proceed ([y]/n)? y


Downloading and Extracting Packages
jinja2-3.1.2         | 99 KB     | ############################################################################################# | 100%
ruamel-1.0           | 5 KB      | ############################################################################################# | 100%
jsonschema-4.5.1     | 57 KB     | ############################################################################################# | 100%
spython-0.2.1        | 68 KB     | ############################################################################################# | 100%
semver-2.13.0        | 15 KB     | ############################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

$ shpc config get module_base
module_base                    /home/nvonwolf/sstack/stacks/conda/testing/envs/shpc/lib/python3.10/site-packages/modules
```

ruamel_yaml isn't specified in the dependencies but it is also required.  I'll open a ticket directly with shpc for that.

Edit:

Had to look it up but it's 'ruamel.yaml' instead of 'ruamel' or 'ruamel_yaml'.  So you can ignore that last part.

**Comment by vsoch** [comment]
oh looks like we need to update some requirements here! https://github.com/conda-forge/singularity-hpc-feedstock/blob/ab63f086bae38ce48b2e7a190e46c356c68cd92a/recipe/meta.yaml#L18-L29 would you care to PR with what you think would work? It looks like maybe this one? https://anaconda.org/conda-forge/ruamel.yaml or this one? https://anaconda.org/conda-forge/ruamel_yaml

**Comment by vsoch** [comment]
I can also do a quick PR if that's easier.

**Comment by vsoch** [comment]
okay here is a first shot https://github.com/conda-forge/singularity-hpc-feedstock/pull/19

**Comment by nlvw** [comment]
@vsoch Thanks for the quick fix.  I'm not too familiar with how conda-forge feedstock works so a PR from me would have taken some time.

Tested your changes and here's the update output:

```console
$ conda create -n shpc python singularity-hpc
...
...
...
$ conda activate shpc
$ conda list
# packages in environment at /home/nvonwolf/sstack/stacks/conda/testing/envs/shpc:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8       py310hff52083_2    conda-forge
cffi                      1.15.0          py310h0fdd8cc_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
cryptography              36.0.2          py310h597c629_1    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3          py310hff52083_1    conda-forge
importlib_resources       5.7.1              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_0    conda-forge
jsonschema                4.5.1              pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
markupsafe                2.1.1           py310h5764c6d_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   1.1.1o               h166bdaf_0    conda-forge
pip                       22.1               pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1          py310h5764c6d_1    conda-forge
pysocks                   1.7.1           py310hff52083_5    conda-forge
python                    3.10.4          h9a8a25e_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.21         py310h5764c6d_1    conda-forge
ruamel.yaml.clib          0.2.6           py310h5764c6d_1    conda-forge
semver                    2.13.0             pyh9f0ad1d_0    conda-forge
setuptools                62.2.0          py310hff52083_0    conda-forge
singularity-hpc           0.0.53             pyhd8ed1ab_2    conda-forge
spython                   0.2.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.38.5               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge

$ shpc config get module_base
module_base                    /home/nvonwolf/sstack/stacks/conda/testing/envs/shpc/lib/python3.10/site-packages/modules
```

I looked at your PR and from the new build, what I can see 'ruamel', 'ruamel_yaml', 'pytest-runner', and 'pytest' are all missing after deployment.  That being said I'm not sure if the ruamel packages conflict with each other (especially 'ruamel.yaml' and 'ruamel_yaml').

Either way the command I was seeing the error for is working now though I'm not sure if other bugs will crop up from this.

**Comment by vsoch** [comment]
Thanks @nlvw - if bugs pop up we will deal with them! I'm most familar using shpc as a clone so it will be good to test out the module install use case more. And of course if we run into any issues we will fix them. Thanks again!

**Comment by nlvw** [comment]
I just looked at https://github.com/conda-forge/singularity-hpc-feedstock/blob/8cb9e9e441627747c61e3d796b77056f5fe90d7a/recipe/meta.yaml#L18-L35 and all of the Run items are there, and they match shpc's listed requirements, so I guess it should be fine (not really sure the difference between run/host).

**Comment by nlvw** [comment]
Ah all my questions answered in https://github.com/conda-forge/singularity-hpc-feedstock/pull/21.

Thanks again for the quick fix and for setting this up for conda-forge.  Makes deployment a breeze!

**Comment by ngam** [comment]
@nlvw did you manage to test again?

noarch/singularity-hpc-0.0.53-pyhd8ed1ab_2.tar.bz2 should be the one that works.

`mamba create -n testing 'singularity-hpc==0.0.53=*pyhd8ed1ab*'` (note the conda notation of `==VERSION=*hash*`, so you can specify singularity-hpc==*=*pyhd8ed1ab*' to get the specific hash). I will soon do a system-wide fix by adding those deps correctly.

**Comment by nlvw** [comment]
I was able to test `singularity-hpc           0.0.53             pyhd8ed1ab_2    conda-forge` as show in my previous post and it worked great.
